# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNGvTJ5n2LTfnZ4KPMO9suxdq5Tv-65g
"""

# Commented out IPython magic to ensure Python compatibility.
# Libraries
!pip install PyPDF2
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# PDF reader
import PyPDF2
# Tokenizer
import collections
from collections import Counter
import re
# %matplotlib inline

# Reading data
from google.colab import files # only needed if you use colab
files.upload() # only needed if you use colab 
# df = pd.read_csv('train.txt')

file = open('MU100Spr14Cahueque.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(file)
print(pdfReader.numPages)

from google.colab import drive
drive.mount('/content/drive')

numOfPages = pdfReader.getNumPages()

text = ""

for i in range(0, numOfPages):
  pageObj = pdfReader.getPage(i)
  print(pageObj.extractText())
  text += pageObj.extractText()

# file.close()

# Cleaning text
# text = pageObj.extractText()
text = text.lower() # Force all words to lowercase
# text = re.sub("[^\w ]", "", text) # Remove all characters that are not a letter or a space
text = re.sub(r'[^A-Za-z0-9 :%]', "", text) # Remove all non enlgish characters except for ':' and '%'
print(text)
text = re.sub(' +', ' ', text) # Remove extra spaces between words
print(text)

# Removing stopwords
import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
stop_words = stopwords.words('english')
stopwords_dict = Counter(stop_words)
text = ' '.join([word for word in text.split() if word not in stopwords_dict])

# Tokenization
words = text.split(" ")
# Counter(words)
print(words)

# Find grading policy
start = text.find("grading:")
print(start)
end = text.find("total")
print(end)
# print(text[start:end])
gradingPolicy = {}


x = re.findall(r"\bexam|midterm|final+", text)
print(x)
# # MNOTES\s?(.{6,8})\s?GEO
# z = re.findall('grading.\s?(.{6,8})\s?:', text)

z = re.findall('grading.(.*?):', text)
print(z)

"""Things to look for
How many exams
How many assignments
What is the grade breakdown
Attendance policy
Grading policy
Disability acommodation
Find similarities, differences between these policies

Use headers to map out sections of a syllabi

Look at 50 words before and after the word exam appears

Check if the word exam is preceeded by a newline character and followed with a newline character in the previous 10 characters
"""